apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: producer}
  name: producer
  namespace: bitnami
spec:
  replicas: 1
  selector:
    matchLabels: {app: producer}
  template:
    metadata:
      labels: {app: producer}
    spec:
      containers:
      - name: producer
        image: pivotalrabbitmq/perf-test
